<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jadwal_menu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jadwal_menu_model');
    } 

    /*
     * Listing of jadwal_menu
     */
    function index()
    {
        $data['jadwal_menu'] = $this->Jadwal_menu_model->get_all_jadwal_menu();
        
        $data['_view'] = 'jadwal_menu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jadwal_menu
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('jadwal','Jadwal','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'jadwal' => $this->input->post('jadwal'),
            );
            
            $jadwal_menu_id = $this->Jadwal_menu_model->add_jadwal_menu($params);
            redirect('jadwal_menu/index');
        }
        else
        {            
            $data['_view'] = 'jadwal_menu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jadwal_menu
     */
    function edit($id_jadwal)
    {   
        // check if the jadwal_menu exists before trying to edit it
        $data['jadwal_menu'] = $this->Jadwal_menu_model->get_jadwal_menu($id_jadwal);
        
        if(isset($data['jadwal_menu']['id_jadwal']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('jadwal','Jadwal','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'jadwal' => $this->input->post('jadwal'),
                );

                $this->Jadwal_menu_model->update_jadwal_menu($id_jadwal,$params);            
                redirect('jadwal_menu/index');
            }
            else
            {
                $data['_view'] = 'jadwal_menu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jadwal_menu you are trying to edit does not exist.');
    } 

    /*
     * Deleting jadwal_menu
     */
    function remove($id_jadwal)
    {
        $jadwal_menu = $this->Jadwal_menu_model->get_jadwal_menu($id_jadwal);

        // check if the jadwal_menu exists before trying to delete it
        if(isset($jadwal_menu['id_jadwal']))
        {
            $this->Jadwal_menu_model->delete_jadwal_menu($id_jadwal);
            redirect('jadwal_menu/index');
        }
        else
            show_error('The jadwal_menu you are trying to delete does not exist.');
    }
    
}
