<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kurang_stok_bahan_makanan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kurang_stok_bahan_makanan_model');
    } 

    /*
     * Listing of kurang_stok_bahan_makanan
     */
    function index()
    {
        $data['kurang_stok_bahan_makanan'] = $this->Kurang_stok_bahan_makanan_model->get_all_kurang_stok_bahan_makanan();
        
        $data['_view'] = 'kurang_stok_bahan_makanan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kurang_stok_bahan_makanan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_bahan' => $this->input->post('id_bahan'),
				'jumlah_bahan' => $this->input->post('jumlah_bahan'),
            );
            
            $kurang_stok_bahan_makanan_id = $this->Kurang_stok_bahan_makanan_model->add_kurang_stok_bahan_makanan($params);
            redirect('kurang_stok_bahan_makanan/index');
        }
        else
        {            
            $data['_view'] = 'kurang_stok_bahan_makanan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kurang_stok_bahan_makanan
     */
    function edit($id)
    {   
        // check if the kurang_stok_bahan_makanan exists before trying to edit it
        $data['kurang_stok_bahan_makanan'] = $this->Kurang_stok_bahan_makanan_model->get_kurang_stok_bahan_makanan($id);
        
        if(isset($data['kurang_stok_bahan_makanan']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_bahan' => $this->input->post('id_bahan'),
					'jumlah_bahan' => $this->input->post('jumlah_bahan'),
                );

                $this->Kurang_stok_bahan_makanan_model->update_kurang_stok_bahan_makanan($id,$params);            
                redirect('kurang_stok_bahan_makanan/index');
            }
            else
            {
                $data['_view'] = 'kurang_stok_bahan_makanan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kurang_stok_bahan_makanan you are trying to edit does not exist.');
    } 

    /*
     * Deleting kurang_stok_bahan_makanan
     */
    function remove($id)
    {
        $kurang_stok_bahan_makanan = $this->Kurang_stok_bahan_makanan_model->get_kurang_stok_bahan_makanan($id);

        // check if the kurang_stok_bahan_makanan exists before trying to delete it
        if(isset($kurang_stok_bahan_makanan['id']))
        {
            $this->Kurang_stok_bahan_makanan_model->delete_kurang_stok_bahan_makanan($id);
            redirect('kurang_stok_bahan_makanan/index');
        }
        else
            show_error('The kurang_stok_bahan_makanan you are trying to delete does not exist.');
    }
    
}
