<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Menu_olah extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Menu_olah_model');
    } 

    /*
     * Listing of menu_olah
     */
    function index()
    {
        $ammount = 20;
        $sender_id = 86;
        $receiver_id = 22;
       
        $this->Menu_olah_model->transaction($ammount, $sender_id, $receiver_id);

        $data['menu_olah'] = $this->Menu_olah_model->get_all_menu_olah();
        
        $data['_view'] = 'menu_olah/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new menu_olah
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_olahan' => $this->input->post('nama_olahan'),
				'Jumlah_Olahan' => $this->input->post('Jumlah_Olahan'),
            );

            
            $menu_olah_id = $this->Menu_olah_model->add_menu_olah($params);
            redirect('menu_olah/index');
        }
        else
        {            
            $data['_view'] = 'menu_olah/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a menu_olah
     */
    function edit($id)
    {   
        // check if the menu_olah exists before trying to edit it
        $data['menu_olah'] = $this->Menu_olah_model->get_menu_olah($id);
        
        if(isset($data['menu_olah']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_olahan' => $this->input->post('nama_olahan'),
					'Jumlah_Olahan' => $this->input->post('Jumlah_Olahan'),
                );

                $this->Menu_olah_model->update_menu_olah($id,$params);            
                redirect('menu_olah/index');
            }
            else
            {
                $data['_view'] = 'menu_olah/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The menu_olah you are trying to edit does not exist.');
    } 

    /*
     * Deleting menu_olah
     */
    function remove($id)
    {
        $menu_olah = $this->Menu_olah_model->get_menu_olah($id);

        // check if the menu_olah exists before trying to delete it
        if(isset($menu_olah['id']))
        {
            $this->Menu_olah_model->delete_menu_olah($id);
            redirect('menu_olah/index');
        }
        else
            show_error('The menu_olah you are trying to delete does not exist.');
    }
    
}
