<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Menu_paket extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Menu_paket_model');
    } 

    /*
     * Listing of menu_paket
     */
    function index()
    {
        $data['menu_paket'] = $this->Menu_paket_model->get_all_menu_paket();
        
        $data['_view'] = 'menu_paket/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new menu_paket
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('menu','Menu','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'menu' => $this->input->post('menu'),
            );
            
            $menu_paket_id = $this->Menu_paket_model->add_menu_paket($params);
            redirect('menu_paket/index');
        }
        else
        {            
            $data['_view'] = 'menu_paket/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a menu_paket
     */
    function edit($id_menu)
    {   
        // check if the menu_paket exists before trying to edit it
        $data['menu_paket'] = $this->Menu_paket_model->get_menu_paket($id_menu);
        
        if(isset($data['menu_paket']['id_menu']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('menu','Menu','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'menu' => $this->input->post('menu'),
                );

                $this->Menu_paket_model->update_menu_paket($id_menu,$params);            
                redirect('menu_paket/index');
            }
            else
            {
                $data['_view'] = 'menu_paket/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The menu_paket you are trying to edit does not exist.');
    } 

    /*
     * Deleting menu_paket
     */
    function remove($id_menu)
    {
        $menu_paket = $this->Menu_paket_model->get_menu_paket($id_menu);

        // check if the menu_paket exists before trying to delete it
        if(isset($menu_paket['id_menu']))
        {
            $this->Menu_paket_model->delete_menu_paket($id_menu);
            redirect('menu_paket/index');
        }
        else
            show_error('The menu_paket you are trying to delete does not exist.');
    }
    
}
