<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Paket extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Paket_model');
    } 

    /*
     * Listing of paket
     */
    function index()
    {
        $data['paket'] = $this->Paket_model->get_all_paket();
        
        $data['_view'] = 'paket/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new paket
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_jadwal','Id Jadwal','required');
		$this->form_validation->set_rules('id_menu','Id Menu','required');
		$this->form_validation->set_rules('nama_paket','Nama Paket','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_jadwal' => $this->input->post('id_jadwal'),
				'id_menu' => $this->input->post('id_menu'),
				'nama_paket' => $this->input->post('nama_paket'),
            );
            
            $paket_id = $this->Paket_model->add_paket($params);
            redirect('paket/index');
        }
        else
        {
			$this->load->model('Jadwal_menu_model');
			$data['all_jadwal_menu'] = $this->Jadwal_menu_model->get_all_jadwal_menu();

			$this->load->model('Menu_paket_model');
			$data['all_menu_paket'] = $this->Menu_paket_model->get_all_menu_paket();
            
            $data['_view'] = 'paket/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a paket
     */
    function edit($id_paket)
    {   
        // check if the paket exists before trying to edit it
        $data['paket'] = $this->Paket_model->get_paket($id_paket);
        
        if(isset($data['paket']['id_paket']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('id_jadwal','Id Jadwal','required');
			$this->form_validation->set_rules('id_menu','Id Menu','required');
			$this->form_validation->set_rules('nama_paket','Nama Paket','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_jadwal' => $this->input->post('id_jadwal'),
					'id_menu' => $this->input->post('id_menu'),
					'nama_paket' => $this->input->post('nama_paket'),
                );

                $this->Paket_model->update_paket($id_paket,$params);            
                redirect('paket/index');
            }
            else
            {
				$this->load->model('Jadwal_menu_model');
				$data['all_jadwal_menu'] = $this->Jadwal_menu_model->get_all_jadwal_menu();

				$this->load->model('Menu_paket_model');
				$data['all_menu_paket'] = $this->Menu_paket_model->get_all_menu_paket();

                $data['_view'] = 'paket/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The paket you are trying to edit does not exist.');
    } 

    /*
     * Deleting paket
     */
    function remove($id_paket)
    {
        $paket = $this->Paket_model->get_paket($id_paket);

        // check if the paket exists before trying to delete it
        if(isset($paket['id_paket']))
        {
            $this->Paket_model->delete_paket($id_paket);
            redirect('paket/index');
        }
        else
            show_error('The paket you are trying to delete does not exist.');
    }
    function ajax_list()
    {
        $list = $this->Paket_model->join_data();
        $data = array();
        $no = $_POST['start'];
        foreach ($list as $p) {
            $row = array();
            $row[] = $p->id_paket;
            $row[] = $p->nama_paket;
            $row[] = $p->menu;
            $row[] = $p->jadwal;
            $row[] = '<a href="edit/'.$p->id_paket.'"class="btn btn-warning btn-xs"><i class="fas fa-cog"></i></a>
                      <a href="remove/'.$p->id_paket.'"class="btn btn-danger btn-xs"><i class="fas fa-trash-alt"></i></a>';
            $data[] = $row;
        }
 
        $output = array(
                        "draw" => $_POST['draw'],
                        "recordsTotal" => $this->Paket_model->count_all(),
                        "recordsFiltered" => $this->Paket_model->count_filtered(),
                        "data" => $data,
                );
        //output to json format
        echo json_encode($output);
    }
    
}
