<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stok_bahan_makanan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Stok_bahan_makanan_model');
        $this->load->library('session');
        $this->load->helper('captcha');

       
    } 

    /*
     * Listing of stok_bahan_makanan
     */
    function index()
    {
        $data['graph'] = $this->Stok_bahan_makanan_model->graph();
        $data['stok_bahan_makanan'] = $this->Stok_bahan_makanan_model->get_all_stok_bahan_makanan();
        
        $data['_view'] = 'stok_bahan_makanan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new stok_bahan_makanan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_bahan','Nama Bahan','required|max_length[30]');
		$this->form_validation->set_rules('jumlah_bahan','Jumlah Bahan','required|max_length[30]');
		
		if($this->form_validation->run())

        {   
            $params = array(
				'kelompok_bahan' => $this->input->post('kelompok_bahan'),
				'nama_bahan' => $this->input->post('nama_bahan'),
				'jumlah_bahan' => $this->input->post('jumlah_bahan'),
            );

            
            $stok_bahan_makanan_id = $this->Stok_bahan_makanan_model->add_stok_bahan_makanan($params);

            redirect('stok_bahan_makanan/index');
        }
        else
        {
			$this->load->model('Kelompok_bahan_makanan_model');
			$data['all_kelompok_bahan_makanan'] = $this->Kelompok_bahan_makanan_model->get_all_kelompok_bahan_makanan();
            
            $data['_view'] = 'stok_bahan_makanan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a stok_bahan_makanan
     */
    function edit($id)
    {   
        // check if the stok_bahan_makanan exists before trying to edit it
        $data['stok_bahan_makanan'] = $this->Stok_bahan_makanan_model->get_stok_bahan_makanan($id);
        
        if(isset($data['stok_bahan_makanan']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_bahan','Nama Bahan','required|max_length[30]');
			$this->form_validation->set_rules('jumlah_bahan','Jumlah Bahan','required|max_length[30]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'kelompok_bahan' => $this->input->post('kelompok_bahan'),
					'nama_bahan' => $this->input->post('nama_bahan'),
					'jumlah_bahan' => $this->input->post('jumlah_bahan'),
                );

                $this->Stok_bahan_makanan_model->update_stok_bahan_makanan($id,$params);            
                redirect('stok_bahan_makanan/index');
            }
            else
            {
				$this->load->model('Kelompok_bahan_makanan_model');
				$data['all_kelompok_bahan_makanan'] = $this->Kelompok_bahan_makanan_model->get_all_kelompok_bahan_makanan();

                $data['_view'] = 'stok_bahan_makanan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The stok_bahan_makanan you are trying to edit does not exist.');
    } 

    /*
     * Deleting stok_bahan_makanan
     */
    function remove($id)
    {
        $stok_bahan_makanan = $this->Stok_bahan_makanan_model->get_stok_bahan_makanan($id);

        // check if the stok_bahan_makanan exists before trying to delete it
        if(isset($stok_bahan_makanan['id']))
        {
            $this->Stok_bahan_makanan_model->delete_stok_bahan_makanan($id);
            redirect('stok_bahan_makanan/index');
        }
        else
            show_error('The stok_bahan_makanan you are trying to delete does not exist.');
    }

     public function export(){
    // Skrip berikut ini adalah skrip yang bertugas untuk meng-export data tadi ke excel
    header("Content-type: application/vnd-ms-excel");
    header("Content-Disposition: attachment; filename=Data_Stok_Bahan_Makanan.xls");
    
    $data['stok_bahan_makanan'] = $this->Stok_bahan_makanan_model->get_all_stok_bahan_makanan();
    $this->load->view('stok_bahan_makanan/export', $data);
  }

   public function cetak(){
    ob_start();
    $data['stok_bahan_makanan'] = $this->Stok_bahan_makanan_model->get_all_stok_bahan_makanan();
    $this->load->view('stok_bahan_makanan/print', $data);
    $html = ob_get_contents();
        ob_end_clean();
        
        require_once('./assets/html2pdf/html2pdf.class.php');
    $pdf = new HTML2PDF('P','A4','en');
    $pdf->WriteHTML($html);
    $pdf->Output('Data Stok Bahan Makanan.pdf', 'D');
  }
  
   function ajax_list()
    {
        $list = $this->Stok_bahan_makanan_model->join_data();
        $data = array();
        $no = $_POST['start'];
        foreach ($list as $stok) {
            $no++;
            $row = array();
            $row[] = $no;
            $row[] = $stok->nama_bahan;
            $row[] = $stok->kelompok;
            $row[] = $stok->jumlah_bahan;
            $row[] = '<a href="edit/'.$stok->id.'"class="btn btn-warning btn-xs"><i class="fas fa-cog"></i></a>
                      <a href="remove/'.$stok->id.'"class="btn btn-danger btn-xs"><i class="fas fa-trash-alt"></i></a>';
            $data[] = $row;
        }
 
        $output = array(
                        "draw" => $_POST['draw'],
                        "recordsTotal" => $this->Stok_bahan_makanan_model->count_all(),
                        "recordsFiltered" => $this->Stok_bahan_makanan_model->count_filtered(),
                        "data" => $data
                );
        //output to json format
        echo json_encode($output);
    }
   

}

 