<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tambah_stok_bahan_makanan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tambah_stok_bahan_makanan_model');
    } 

    /*
     * Listing of tambah_stok_bahan_makanan
     */
    function index()
    {
        $data['tambah_stok_bahan_makanan'] = $this->Tambah_stok_bahan_makanan_model->get_all_tambah_stok_bahan_makanan();
        
        $data['_view'] = 'tambah_stok_bahan_makanan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tambah_stok_bahan_makanan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_bahan' => $this->input->post('id_bahan'),
				'jumlah_bahan' => $this->input->post('jumlah_bahan'),
            );
            
            $tambah_stok_bahan_makanan_id = $this->Tambah_stok_bahan_makanan_model->add_tambah_stok_bahan_makanan($params);
            redirect('tambah_stok_bahan_makanan/index');
        }
        else
        {            
            $data['_view'] = 'tambah_stok_bahan_makanan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tambah_stok_bahan_makanan
     */
    function edit($id)
    {   
        // check if the tambah_stok_bahan_makanan exists before trying to edit it
        $data['tambah_stok_bahan_makanan'] = $this->Tambah_stok_bahan_makanan_model->get_tambah_stok_bahan_makanan($id);
        
        if(isset($data['tambah_stok_bahan_makanan']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_bahan' => $this->input->post('id_bahan'),
					'jumlah_bahan' => $this->input->post('jumlah_bahan'),
                );

                $this->Tambah_stok_bahan_makanan_model->update_tambah_stok_bahan_makanan($id,$params);            
                redirect('tambah_stok_bahan_makanan/index');
            }
            else
            {
                $data['_view'] = 'tambah_stok_bahan_makanan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tambah_stok_bahan_makanan you are trying to edit does not exist.');
    } 

    /*
     * Deleting tambah_stok_bahan_makanan
     */
    function remove($id)
    {
        $tambah_stok_bahan_makanan = $this->Tambah_stok_bahan_makanan_model->get_tambah_stok_bahan_makanan($id);

        // check if the tambah_stok_bahan_makanan exists before trying to delete it
        if(isset($tambah_stok_bahan_makanan['id']))
        {
            $this->Tambah_stok_bahan_makanan_model->delete_tambah_stok_bahan_makanan($id);
            redirect('tambah_stok_bahan_makanan/index');
        }
        else
            show_error('The tambah_stok_bahan_makanan you are trying to delete does not exist.');
    }
    
}
