<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jadwal_menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jadwal_menu by id_jadwal
     */
    function get_jadwal_menu($id_jadwal)
    {
        return $this->db->get_where('jadwal_menu',array('id_jadwal'=>$id_jadwal))->row_array();
    }
        
    /*
     * Get all jadwal_menu
     */
    function get_all_jadwal_menu()
    {
        $this->db->order_by('id_jadwal', 'desc');
        return $this->db->get('jadwal_menu')->result_array();
    }
        
    /*
     * function to add new jadwal_menu
     */
    function add_jadwal_menu($params)
    {
        $this->db->insert('jadwal_menu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jadwal_menu
     */
    function update_jadwal_menu($id_jadwal,$params)
    {
        $this->db->where('id_jadwal',$id_jadwal);
        return $this->db->update('jadwal_menu',$params);
    }
    
    /*
     * function to delete jadwal_menu
     */
    function delete_jadwal_menu($id_jadwal)
    {
        return $this->db->delete('jadwal_menu',array('id_jadwal'=>$id_jadwal));
    }
}
