<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kurang_stok_bahan_makanan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kurang_stok_bahan_makanan by id
     */
    function get_kurang_stok_bahan_makanan($id)
    {
        return $this->db->get_where('kurang_stok_bahan_makanan',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all kurang_stok_bahan_makanan
     */
    function get_all_kurang_stok_bahan_makanan()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('kurang_stok_bahan_makanan')->result_array();
    }
        
    /*
     * function to add new kurang_stok_bahan_makanan
     */
    function add_kurang_stok_bahan_makanan($params)
    {
        $this->db->insert('kurang_stok_bahan_makanan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kurang_stok_bahan_makanan
     */
    function update_kurang_stok_bahan_makanan($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('kurang_stok_bahan_makanan',$params);
    }
    
    /*
     * function to delete kurang_stok_bahan_makanan
     */
    function delete_kurang_stok_bahan_makanan($id)
    {
        return $this->db->delete('kurang_stok_bahan_makanan',array('id'=>$id));
    }
}
