<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Menu_olah_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get menu_olah by id
     */
    function get_menu_olah($id)
    {
        return $this->db->get_where('menu_olah',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all menu_olah
     */
    function get_all_menu_olah()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('menu_olah')->result_array();
    }
        
    /*
     * function to add new menu_olah
     */
    function add_menu_olah($params)
    {
        $this->db->insert('menu_olah',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update menu_olah
     */
    function update_menu_olah($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('menu_olah',$params);
    }
    
    /*
     * function to delete menu_olah
     */
    function delete_menu_olah($id)
    {
        return $this->db->delete('menu_olah',array('id'=>$id));
    }
    function transaction($ammount, $from, $to)
    {
        $sender = 'UPDATE stok_bahan_makanan SET jumlah_bahan = jumlah_bahan - ? where id = ?';
        $receiver = 'UPDATE menu_olah SET Jumlah_Olahan = Jumlah_Olahan + ? where id = ?';

        $this->db->trans_start();
        $this->db->query($sender, array($ammount, $from));
        $this->db->query($receiver, array($ammount, $to));
        $this->db->trans_complete();

        if ($this->db->trans_status() === false) {
            echo 'rollback!';  
        }else{
            echo 'commited';
        }
    }
}
