<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Menu_paket_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get menu_paket by id_menu
     */
    function get_menu_paket($id_menu)
    {
        return $this->db->get_where('menu_paket',array('id_menu'=>$id_menu))->row_array();
    }
        
    /*
     * Get all menu_paket
     */
    function get_all_menu_paket()
    {
        $this->db->order_by('id_menu', 'desc');
        return $this->db->get('menu_paket')->result_array();
    }
        
    /*
     * function to add new menu_paket
     */
    function add_menu_paket($params)
    {
        $this->db->insert('menu_paket',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update menu_paket
     */
    function update_menu_paket($id_menu,$params)
    {
        $this->db->where('id_menu',$id_menu);
        return $this->db->update('menu_paket',$params);
    }
    
    /*
     * function to delete menu_paket
     */
    function delete_menu_paket($id_menu)
    {
        return $this->db->delete('menu_paket',array('id_menu'=>$id_menu));
    }
}
