<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tambah_stok_bahan_makanan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tambah_stok_bahan_makanan by id
     */
    function get_tambah_stok_bahan_makanan($id)
    {
        return $this->db->get_where('tambah_stok_bahan_makanan',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tambah_stok_bahan_makanan
     */
    function get_all_tambah_stok_bahan_makanan()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tambah_stok_bahan_makanan')->result_array();
    }
        
    /*
     * function to add new tambah_stok_bahan_makanan
     */
    function add_tambah_stok_bahan_makanan($params)
    {
        $this->db->insert('tambah_stok_bahan_makanan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tambah_stok_bahan_makanan
     */
    function update_tambah_stok_bahan_makanan($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tambah_stok_bahan_makanan',$params);
    }
    
    /*
     * function to delete tambah_stok_bahan_makanan
     */
    function delete_tambah_stok_bahan_makanan($id)
    {
        return $this->db->delete('tambah_stok_bahan_makanan',array('id'=>$id));
    }
}
